<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Home</title>
</head>
<body style="background-color: #D8D8D8;">

<% 

response.setHeader("Cache-Control","no-cache,no-store,must-revalidate");
// response.setHeader("Pragma","no-cache");       //for http 1.0 and below
//response.setHeader("Expires","0");              //for proxies

if(session.getAttribute("username")==null)
 {
	response.sendRedirect("login.jsp");
 }
%>
<%@ include file="header.jsp" %>
<br/>

 <article>
<h1 id="top10"><b><i><u>TOP 10 MOVIES OF ALL TIME</u></i></b></h1>


<br/>
<dl>
<dt><h2><u><i>1. The Godfather (1972)</i></u></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp      <img height="400px" width="350px" src="http://im.rediff.com/getahead/2014/jun/16film16.jpg"/><br/><br/>
<i>The Godfather is a 1972 American crime film directed by Francis Ford Coppola and produced by Albert S. Ruddy, based on Mario Puzo's best-selling eponymous novel. It stars Marlon Brando and Al Pacino as the leaders of a fictional New York crime family. The story, spanning 1945 to 1955, chronicles the family under the patriarch Vito Corleone (Brando), focusing on the transformation of Michael Corleone (Pacino) from reluctant family outsider to ruthless mafia boss.
Paramount Pictures obtained the rights to the novel for the price of $80,000, before it gained popularity. Studio executives had trouble finding a director; their first few candidates turned down the position. They and Coppola disagreed over who would play several characters, in particular, Vito and Michael. Filming was done on location and completed earlier than scheduled. The musical score was composed primarily by Nino Rota with additional pieces by Carmine Coppola.
The film was the highest-grossing film of 1972 and was for a time the highest-grossing film ever made. It won the Oscars for Best Picture, Best Actor (Brando) and Best Adapted Screenplay (for Puzo and Coppola). Its seven other Oscar nominations included Pacino, James Caan, and Robert Duvall for Best Supporting Actor and Coppola for Best Director.</i><a href="http://www.imdb.com/title/tt0068646/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" src="https://gracezylbee.files.wordpress.com/2018/02/g-4.jpg"/>
</dd>
</dl>
<dt><h2><u><i>2. Shawshank Redemption (1994)</i></u></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img height="400px" width="350px" src="https://static.rogerebert.com/uploads/movie/movie_poster/the-shawshank-redemption-1994/large_9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg"><br/><br/>
<i>The Shawshank Redemption is a 1994 American drama film written and directed by Frank Darabont, based on the Stephen King novella Rita Hayworth and Shawshank Redemption. It tells the story of banker Andy Dufresne (Tim Robbins), who is sentenced to life in Shawshank State Penitentiary for the murder of his wife and her lover, despite his claims of innocence. Over the following two decades, he befriends a fellow prisoner, contraband smuggler Ellis "Red" Redding (Morgan Freeman), and becomes instrumental in a money laundering operation led by the prison warden Samuel Norton (Bob Gunton). The film also stars William Sadler, Clancy Brown, Gil Bellows, and James Whitmore.
Darabont purchased the film rights to King's story in 1987, but development did not begin until five years later when he wrote the script over an eight-week period. Two weeks after submitting his script to the Castle Rock Entertainment film studio, Darabont secured a $25 million budget to produce The Shawshank Redemption, which started pre-production in January 1993. While the film is set in Maine, principal photography took place almost entirely in Mansfield, Ohio, with the Ohio State Reformatory serving as the eponymous penitentiary. The project attracted many notable stars of the time for the lead roles including Tom Hanks, Tom Cruise, and Kevin Costner. Thomas Newman provided the film's score.</i><a href="http://www.imdb.com/title/tt0111161/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" width="350px"src="http://www.onewhowakes.org/wp-content/uploads/2013/11/the_shawshank_redemption_by_rikud0k0-d5rpssf.jpg?x21307"/>
</dd>
<dt><h2><u><i>3. Schindler's List (1993)</u></i></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img height="400px" width="350px" src="http://www.myfreewallpapers.net/movies/wallpapers/schindlers-list.jpg"><br/><br/>
<i>Schindler's List is a 1993 American epic historical period drama film directed and co-produced by Steven Spielberg and scripted by Steven Zaillian. It is based on the novel Schindler's Ark by Australian novelist Thomas Keneally. The film relates a period in the life of Oskar Schindler, an ethnic German businessman, during which he saved the lives of more than a thousand mostly Polish-Jewish refugees from the Holocaust by employing them in his factories during World War II. It stars Liam Neeson as Schindler, Ralph Fiennes as SS officer Amon Göth, and Ben Kingsley as Schindler's Jewish accountant Itzhak Stern.
Ideas for a film about the Schindlerjuden (Schindler Jews) were proposed as early as 1963. Poldek Pfefferberg, one of the Schindlerjuden, made it his life's mission to tell the story of Schindler. Spielberg became interested in the story when executive Sidney Sheinberg sent him a book review of Schindler's Ark. Universal Pictures bought the rights to the novel, but Spielberg, unsure if he was ready to make a film about the Holocaust, tried to pass the project to several other directors before finally deciding to direct the film himself.<a href="http://www.imdb.com/title/tt0108052/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" width="350px" src="https://images-na.ssl-images-amazon.com/images/M/MV5BMjExNzg2OTYwMF5BMl5BanBnXkFtZTgwOTY1NjQ3MjI@._V1_CR0,59,640,360_AL_UX477_CR0,0,477,268_AL_.jpg"/>
</i></dd>
<dt><h2><u><i>4. Raging Bull (1980)</u></i></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img height="400px" width="350px" src="https://static.rogerebert.com/uploads/movie/movie_poster/raging-bull-1980/large_wWVfkkt40Jn8P0SVxFt8Dr46LPK.jpg"><br/><br/>
<i>Raging Bull is a 1980 American biographical black-and-white sports drama film directed by Martin Scorsese, produced by Robert Chartoff and Irwin Winkler and adapted by Paul Schrader and Mardik Martin from Jake LaMotta's memoir Raging Bull: My Story. It stars Robert De Niro as Jake LaMotta, an Italian American middleweight boxer whose self-destructive and obsessive rage, sexual jealousy, and animalistic appetite destroyed his relationship with his wife and family. Also featured in the film are Joe Pesci as Joey, LaMotta's well-intentioned brother and manager who tries to help Jake battle his inner demons, and Cathy Moriarty as his wife. The film features supporting roles from Nicholas Colasanto, Theresa Saldana, and Frank Vincent.
Scorsese was initially reluctant to develop the project, though he eventually came to relate to LaMotta's story. Schrader re-wrote Martin's first screenplay, and Scorsese and De Niro together made uncredited contributions thereafter. Pesci was an unknown actor prior to the film, as was Moriarty, who was suggested for her role by Pesci. During principal photography, each of the boxing scenes was choreographed for a specific visual style and De Niro gained approximately 60 pounds (27 kg) to portray LaMotta in his later post-boxing years. Scorsese was exacting in the process of editing and mixing the film, expecting it to be his last major feature.</i>
<a href="http://www.imdb.com/title/tt0081398/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" width="350px" src="https://upload.wikimedia.org/wikipedia/en/5/5f/Raging_Bull_poster.jpg"/>
</dd>
<dt><h2><u><i>5. Casablanca (1942)</u></i></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img height="400px" width="350px" src="https://images-na.ssl-images-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX182_CR0,0,182,268_AL__QL50.jpg"><br/><br/>
<i>Casablanca is a 1942 American romantic drama film directed by Michael Curtiz and based on Murray Burnett and Joan Alison's unproduced stage play Everybody Comes to Rick's. The film stars Humphrey Bogart, Ingrid Bergman, and Paul Henreid; it also features Claude Rains, Conrad Veidt, Sydney Greenstreet, Peter Lorre, and Dooley Wilson. Set during World War II, it focuses on an American expatriate who must choose between his love for a woman and helping her and her husband, a Czech Resistance leader, escape from the Vichy-controlled city of Casablanca to continue his fight against the Nazis.Story editor Irene Diamond convinced producer Hal B. Wallis to purchase the film rights to the play in January 1942. Brothers Julius and Philip G. Epstein were initially assigned to write the script. However, despite studio resistance, they left to work on Frank Capra's Why We Fight series early in 1942. Howard E. Koch was assigned to the screenplay until the Epsteins returned a month later. Principal photography began on May 25, 1942, ending on August 3; the film was shot entirely at Warner Bros. Studios in Burbank, California with the exception of one sequence at Van Nuys Airport in Van Nuys, Los Angeles.</i>
<a href="http://www.imdb.com/title/tt0034583/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" width="350px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVF7MUzN34ijH3miHxyJ5UNhb4XiodaVl4vDpKEnAfnDpMv9x2"/>
</dd>
<dt><h2><u><i>6.Citizen Kane (1941)</u></i></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img height="400px" width="350px" src="https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2Mjc1MDQwMl5BMl5BanBnXkFtZTcwNzUyOTUyMg@@._V1_UX182_CR0,0,182,268_AL__QL50.jpg"><br/><br/>
<i>Citizen Kane is a 1941 American mystery drama film by Orson Welles, its producer, co-screenwriter, director and star. The picture was Welles's first feature film. Nominated for Academy Awards in nine categories, it won an Academy Award for Best Writing (Original Screenplay) by Herman J. Mankiewicz and Welles. Considered by many critics, filmmakers, and fans to be the greatest film of all time, Citizen Kane was voted as such in five consecutive British Film Institute Sight & Sound polls of critics, until it was displaced by Vertigo in the 2012 poll. It topped the American Film Institute's 100 Years ... 100 Movies list in 1998, as well as its 2007 update. Citizen Kane is particularly praised for its cinematography, music, editing and narrative structure, which have been considered innovative and precedent-setting.The quasi-biographical film examines the life and legacy of Charles Foster Kane, played by Welles, a character based in part upon the American newspaper magnate William Randolph Hearst, Chicago tycoons Samuel Insull and Harold McCormick, and aspects of Welles's own life. Upon its release, Hearst prohibited mention of the film in any of his newspapers.</i>
<a href="http://www.imdb.com/title/tt0033467/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" width="350px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH5Z2jdUD89uG0MDUno6PGBBudNu3pNqCVriw0B1H3SQVhgvSrpg"/>
</dd>
<dt><h2><u><i>7.Gone with the Wind (1939)</u></i></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img height="400px" width="350px" src="https://images-na.ssl-images-amazon.com/images/M/MV5BYWQwOWVkMGItMDU2Yy00YjIzLWJkMjEtNmVkZjE3MjMwYzEzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1._SX140_CR0,0,140,209_.jpg"><br/><br/>
<i>Gone with the Wind is a 1939 American epic historical romance film adapted from Margaret Mitchell's 1936 novel of the same name. The film was produced by David O. Selznick of Selznick International Pictures and directed by Victor Fleming. Set in the American South against the backdrop of the American Civil War and Reconstruction era, the film tells the story of Scarlett O'Hara, the strong-willed daughter of a Georgia plantation owner, from her romantic pursuit of Ashley Wilkes, who is married to his cousin, Melanie Hamilton, to her marriage to Rhett Butler. The leading roles are portrayed by Vivien Leigh (Scarlett), Clark Gable (Rhett), Leslie Howard (Ashley), and Olivia de Havilland (Melanie).Production was difficult from the start. Filming was delayed for two years due to Selznick's determination to secure Gable for the role of Rhett Butler, and the "search for Scarlett" led to 1,400 women being interviewed for the part. The original screenplay was written by Sidney Howard, but underwent many revisions by several writers in an attempt to get it down to a suitable length. The original director, George Cukor, was fired shortly after filming had begun and was replaced by Fleming, who in turn was briefly replaced by Sam Wood while Fleming took some time off due to exhaustion.</i>
<a href="http://www.imdb.com/title/tt0031381/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" width="350px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ38arjLAi1lNhAq2kZBHWgV0r4oAalonFuTv2bfUifQTBZ_Ndy"/>
</dd>
<dt><h2><u><i>8. The Wizard of Oz (1939)</u></i></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img height="400px" width="350px" src="https://images-na.ssl-images-amazon.com/images/M/MV5BNjUyMTc4MDExMV5BMl5BanBnXkFtZTgwNDg0NDIwMjE@._V1_UX182_CR0,0,182,268_AL__QL50.jpg"><br/><br/>
<i>The Wizard of Oz is a 1939 American musical fantasy film produced by Metro-Goldwyn-Mayer. Widely considered to be one of the greatest films in cinema history, it is the best-known and most commercially successful adaptation of L. Frank Baum's 1900 children's book, The Wonderful Wizard of Oz.[6] It stars Judy Garland as Dorothy Gale, alongside Ray Bolger, Jack Haley, Bert Lahr, Frank Morgan, Billie Burke and Margaret Hamilton, with Charley Grapewin, Pat Walshe and Clara Blandick, Terry (billed as Toto), and the Singer Midgets as the Munchkins.Notable for its use of Technicolor, fantasy storytelling, musical score, and memorable characters, it has become an icon of American popular culture. It was nominated for six Academy Awards, including Best Picture, but lost to Gone with the Wind. It did win in two other categories, including Best Original Song for "Over the Rainbow" and Best Original Score by Herbert Stothart. While the film was considered a critical success upon release in August 1939, it failed to generate profit for MGM, earning only $3,017,000 on a $2,777,000 budget, which made it MGM's most expensive production to date.</i>
<a href="http://www.imdb.com/title/tt0032138/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" width="350px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKZUecNQVjIIQtpUajfB6vr0XYn3mH1XDsvEZ99dnmo2G3DkM8iA"/>
</dd>
<dt><h2><u><i>9. One Flew Over the Cuckoo's Nest (1975)</u></i></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img height="400px" width="350px" src="https://images-na.ssl-images-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL__QL50.jpg"><br/><br/>
<i>One Flew Over the Cuckoo's Nest is a 1975 American comedy-drama film directed by Miloš Forman, based on the 1962 novel One Flew Over the Cuckoo's Nest by Ken Kesey. The film stars Jack Nicholson, and features a supporting cast of Louise Fletcher, William Redfield, Will Sampson, and Brad Dourif. Considered to be one of the greatest films ever made, One Flew Over the Cuckoo's Nest is No. 33 on the American Film Institute's 100 Years... 100 Movies list. The film was the second to win all five major Academy Awards (Best Picture, Actor in Lead Role, Actress in Lead Role, Director, and Screenplay) following It Happened One Night in 1934, an accomplishment not repeated until 1991 by The Silence of the Lambs. It also won numerous Golden Globe and BAFTA Awards.</i>
<a href="http://www.imdb.com/title/tt0073486/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" width="350px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn_B_fgIwRR_6Qtq5YztdYnChX5Ts5OR0qWm0D7veE7Ey07jlD"/>
</dd>
<dt><h2><u><i>10. Lawrence of Arabia (1962)</u></i></h2></dt>
<dd>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img height="400px" width="350px" src="https://images-na.ssl-images-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UY268_CR2,0,182,268_AL__QL50.jpg"><br/><br/>
<i>Lawrence of Arabia is a 1962 epic historical drama film based on the life of T. E. Lawrence. It was directed by David Lean and produced by Sam Spiegel through his British company Horizon Pictures, with the screenplay by Robert Bolt and Michael Wilson. The film stars Peter O'Toole in the title role. It is widely considered one of the greatest and most influential films in the history of cinema. The dramatic score by Maurice Jarre and the Super Panavision 70 cinematography by Freddie Young are also highly acclaimed.The film was nominated for ten Oscars at the 35th Academy Awards in 1963; it won seven in total: Best Picture, Best Director, Best Original Score, Best Cinematography (Color), Best Art Direction (Color), Best Film Editing and Best Sound Mixing. It also won the Golden Globe Award for Best Motion Picture - Drama and the BAFTA Awards for Best Film and Outstanding British Film.</i>
<a href="http://www.imdb.com/title/tt0056172/" target="_blank">(see more....)</a><br/><br/>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img align="center" height="400px" width="350px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSERejeCeHKeYH--hk6s4zuAbQbXttNsJYHS7uti8WOieG1TD0_"/>
</dd>
</article>
<br/>
<%@include file="footer.jsp" %>
</body>
</html>